site_name: "Starve Style : A C++ Coding Guideline"
site_url: https://belphonz.github.io/Starve-Style

theme:
  name: 'material'
  palette:
    scheme: slate
    primary: white
    accent: indigo
  logo: assets/logo.png
  favicon: assets/logo.png
  language: en
  features:
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.indexes
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
nav:
  - index.md
  - Global Scope :
    - Global_Scope/index.md
    - Global_Scope/Header-Guard.md
    - Global_Scope/Include-Directives-Layout.md
    - Global_Scope/Naming-Conventions-Namespaces.md
    - Global_Scope/Global-Variables.md
    - Global_Scope/File-And-Folder-Naming.md
  - Local Scope Within Main :
    - Local_Scope_Within_Main/index.md
    - Local_Scope_Within_Main/Initialization.md
    - Local_Scope_Within_Main/Naming-Conventions-Variables.md
    - Local_Scope_Within_Main/Scope.md
    - Local_Scope_Within_Main/Pointer-and-Reference-Notation.md
  - Complex Type Scope :
    - Complex_Type_Scope/index.md
    - Complex_Type_Scope/Naming-Conventions-Complex-Type-Names.md
    - Complex_Type_Scope/Complex-Type-Layout.md
    - Complex_Type_Scope/Naming-Conventions-Attributes-and-Methods.md
    - Complex_Type_Scope/Naming-Conventions-Template-Parameters.md
  - Function Scope :
    - Function_Scope/index.md
  - Scope in Flow Control Statements :
    - Scope_In_Flow_Control_Statements/index.md
    - Scope_In_Flow_Control_Statements/Naming-Conventions-Loop-Index.md
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Belphonz
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/AethelCrown
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/aethel-crown/
    - icon: fontawesome/solid/envelope
      link: mailto:<aethel.crown@gmail.copm>
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - toc:
      toc_depth: 3 
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences    

plugins:
  - search

