site_name: "Starve Style : A C++ Coding Guideline"
site_url: https://belphonz.github.io/Starve-Style
theme:
    name: material
    #palette:  
   # - media: "(prefers-color-scheme: dark)"
    #  scheme: slate
    #  primary: pink
    #  accent: blue

