site_name: "Starve Style : A C++ Coding Guideline"
site_url: https://belphonz.github.io/Starve-Style

theme:
  name: 'material'
  palette:
    scheme: slate
    primary: cyan
    accent: teal
  logo: assets/logo.png
  favicon: assets/logo.png
  language: en
  features:
    - navigation.footer
    - navigation.path
    - navigation.instant
    - navigation.instant.progress
    - navigation.indexes
    - content.code.copy
nav:
  - index.md
  - Global Scope :
    - Global-Scope/index.md
    - Global-Scope/Header-Guard.md
    - Global-Scope/Include-Directives-Layout.md
    - Global-Scope/Naming-Conventions-Namespaces.md
    - Global-Scope/Naming-Conventions-Constants.md
  - Local Scope Within Main :
    - Local-Scope-Within-Main/index.md
    - Local-Scope-Within-Main/Initialization.md
    - Local-Scope-Within-Main/Naming-Conventions-Variables.md
    - Local-Scope-Within-Main/Scope.md
    - Local-Scope-Within-Main/Pointer-and-Reference-Notation.md
  - Complex Type Scope :
    - Complex-Type-Scope/index.md
    - Complex-Type-Scope/Naming-Conventions-Complex-Type-Names.md
    - Complex-Type-Scope/Complex-Type-Layout.md
    - Complex-Type-Scope/Naming-Conventions-Attributes-and-Methods.md
    - Complex-Type-Scope/Naming-Conventions-Template-Parameters.md
  - Function Scope :
    - Function-Scope/index.md
  - Scope in Flow Control Statements :
    - Scope-in-Flow-Control-Statements/index.md
    - Scope-in-Flow-Control-Statements/Naming-Conventions-Loop-Index.md
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Belphonz
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/AethelCrown
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/aethel-crown/
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - toc:
      toc_depth: 3 
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences    

plugins:
  - search
