site_name: "Starve Style : A C++ Coding Guideline"
site_url: https://belphonz.github.io/Starve-Style
theme:
    name: 'material'
    logo: assets/logo.png
    favicon: assets/logo.png
    primary: cyan
    accent: teal
    features:
      - navigation.footer
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Belphonz
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/AethelCrown
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/aethel-crown/
     

# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - toc:
      permalink: true

plugins:
  - search

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 