site_name: "Starve Style : A C++ Coding Guideline"

theme:
    name: material
    #palette:  
   # - media: "(prefers-color-scheme: dark)"
    #  scheme: slate
    #  primary: pink
    #  accent: blue

