site_name: "Starve Style : A C++ Coding Guideline"
site_url: https://belphonz.github.io/Starve-Style

theme:
    name: 'material'
    logo: assets/logo.png
    favicon: assets/logo.png
    primary: cyan
    accent: teal
    features:
      - navigation.footer
      - navigation.path
      - navigation.sections

      - navigation.instant
      - navigation.instant.progress
	  - content.code.copy
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Belphonz
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/AethelCrown
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/aethel-crown/
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - toc:
      toc_depth: 3 
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences    

plugins:
  - search
