site_name: "Starve Style : A C++ Coding Guideline"
site_url: https://belphonz.github.io/Starve-Style

theme:
    name: 'material'
    logo: assets/logo.png
    favicon: assets/logo.png
    primary: cyan
    accent: teal
    features:
      - navigation.footer
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Belphonz
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/AethelCrown
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/aethel-crown/
extra_css:
  - stylesheets/extra.css
     


plugins:
  - search
